/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
import { MatchResults } from "@stencil-community/router";
export namespace Components {
    interface AppHome {
    }
    interface AppProfile {
        "match": MatchResults;
    }
    interface AppRoot {
    }
    interface StenduxCounter {
    }
    interface UiBtn {
    }
}
declare global {
    interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {
    }
    var HTMLAppHomeElement: {
        prototype: HTMLAppHomeElement;
        new (): HTMLAppHomeElement;
    };
    interface HTMLAppProfileElement extends Components.AppProfile, HTMLStencilElement {
    }
    var HTMLAppProfileElement: {
        prototype: HTMLAppProfileElement;
        new (): HTMLAppProfileElement;
    };
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLStenduxCounterElement extends Components.StenduxCounter, HTMLStencilElement {
    }
    var HTMLStenduxCounterElement: {
        prototype: HTMLStenduxCounterElement;
        new (): HTMLStenduxCounterElement;
    };
    interface HTMLUiBtnElement extends Components.UiBtn, HTMLStencilElement {
    }
    var HTMLUiBtnElement: {
        prototype: HTMLUiBtnElement;
        new (): HTMLUiBtnElement;
    };
    interface HTMLElementTagNameMap {
        "app-home": HTMLAppHomeElement;
        "app-profile": HTMLAppProfileElement;
        "app-root": HTMLAppRootElement;
        "stendux-counter": HTMLStenduxCounterElement;
        "ui-btn": HTMLUiBtnElement;
    }
}
declare namespace LocalJSX {
    interface AppHome {
    }
    interface AppProfile {
        "match"?: MatchResults;
    }
    interface AppRoot {
    }
    interface StenduxCounter {
    }
    interface UiBtn {
        "onClick"?: (event: CustomEvent<any>) => void;
    }
    interface IntrinsicElements {
        "app-home": AppHome;
        "app-profile": AppProfile;
        "app-root": AppRoot;
        "stendux-counter": StenduxCounter;
        "ui-btn": UiBtn;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-home": LocalJSX.AppHome & JSXBase.HTMLAttributes<HTMLAppHomeElement>;
            "app-profile": LocalJSX.AppProfile & JSXBase.HTMLAttributes<HTMLAppProfileElement>;
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "stendux-counter": LocalJSX.StenduxCounter & JSXBase.HTMLAttributes<HTMLStenduxCounterElement>;
            "ui-btn": LocalJSX.UiBtn & JSXBase.HTMLAttributes<HTMLUiBtnElement>;
        }
    }
}
