/* eslint-disable */
/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */
import { HTMLStencilElement, JSXBase } from "@stencil/core/internal";
export namespace Components {
    interface AppRoot {
    }
    interface SteduxAsync {
    }
    interface SteduxCounter {
    }
    interface UiBtn {
    }
    interface UiJumbo {
    }
}
declare global {
    interface HTMLAppRootElement extends Components.AppRoot, HTMLStencilElement {
    }
    var HTMLAppRootElement: {
        prototype: HTMLAppRootElement;
        new (): HTMLAppRootElement;
    };
    interface HTMLSteduxAsyncElement extends Components.SteduxAsync, HTMLStencilElement {
    }
    var HTMLSteduxAsyncElement: {
        prototype: HTMLSteduxAsyncElement;
        new (): HTMLSteduxAsyncElement;
    };
    interface HTMLSteduxCounterElement extends Components.SteduxCounter, HTMLStencilElement {
    }
    var HTMLSteduxCounterElement: {
        prototype: HTMLSteduxCounterElement;
        new (): HTMLSteduxCounterElement;
    };
    interface HTMLUiBtnElement extends Components.UiBtn, HTMLStencilElement {
    }
    var HTMLUiBtnElement: {
        prototype: HTMLUiBtnElement;
        new (): HTMLUiBtnElement;
    };
    interface HTMLUiJumboElement extends Components.UiJumbo, HTMLStencilElement {
    }
    var HTMLUiJumboElement: {
        prototype: HTMLUiJumboElement;
        new (): HTMLUiJumboElement;
    };
    interface HTMLElementTagNameMap {
        "app-root": HTMLAppRootElement;
        "stedux-async": HTMLSteduxAsyncElement;
        "stedux-counter": HTMLSteduxCounterElement;
        "ui-btn": HTMLUiBtnElement;
        "ui-jumbo": HTMLUiJumboElement;
    }
}
declare namespace LocalJSX {
    interface AppRoot {
    }
    interface SteduxAsync {
    }
    interface SteduxCounter {
    }
    interface UiBtn {
    }
    interface UiJumbo {
    }
    interface IntrinsicElements {
        "app-root": AppRoot;
        "stedux-async": SteduxAsync;
        "stedux-counter": SteduxCounter;
        "ui-btn": UiBtn;
        "ui-jumbo": UiJumbo;
    }
}
export { LocalJSX as JSX };
declare module "@stencil/core" {
    export namespace JSX {
        interface IntrinsicElements {
            "app-root": LocalJSX.AppRoot & JSXBase.HTMLAttributes<HTMLAppRootElement>;
            "stedux-async": LocalJSX.SteduxAsync & JSXBase.HTMLAttributes<HTMLSteduxAsyncElement>;
            "stedux-counter": LocalJSX.SteduxCounter & JSXBase.HTMLAttributes<HTMLSteduxCounterElement>;
            "ui-btn": LocalJSX.UiBtn & JSXBase.HTMLAttributes<HTMLUiBtnElement>;
            "ui-jumbo": LocalJSX.UiJumbo & JSXBase.HTMLAttributes<HTMLUiJumboElement>;
        }
    }
}
